Lab2/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab2.Controllers
{
    public class GradesController : Controller
    {
        // GET: Grades
        [HttpGet]
        public ActionResult IndexGrades()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IndexGrades(FormCollection form)
        {
            ViewData["letterGrade"] = "";
            if (form["gradeOne"] == null && form["gradeTwo"] == null && form["gradeThree"] == null) {    
                    ViewData["letterGrade"] = "You must fill out all the form";
            }
            else{
                double firstGrade = double.Parse(form["gradeOne"]);
                double secondGrade = double.Parse(form["gradeTwo"]);
                double thirdGrade = double.Parse(form["gradeThree"]);
                double average = (firstGrade + secondGrade + thirdGrade) / 3;

                if (average >= 90 && average <= 100) {
                    ViewData["letterGrade"] = "Your letter grade is A";
                } else if (average >= 80 && average <= 89) {
                    ViewData["letterGrade"] = "Your letter grade is B";
                } else if (average >= 70 && average <= 79) {
                    ViewData["letterGrade"] = "Your letter grade is C";
                } else if (average >= 60 && average <= 69) {
                    ViewData["letterGrade"] = "Your letter grade is D";
                } else if (average <= 59) {
                    ViewData["letterGrade"] = "Your letter grade is F";
                }
            } 
            return View();
        }
    }
}

Lab2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab2.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

    }
}

Lab2/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab2.Controllers
{
    public class LoanController : Controller
    {
        // GET: Loan
        [HttpGet]
        public ActionResult IndexLoan()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IndexLoan(double years, double amount, double rate)
        {
            ViewData["years"] = years;
            ViewData["amount"] = amount;
            ViewData["rate"] = rate;
            for (int x = 0; x < years; x++) {
                amount += (rate / 100) * amount;
            }
            ViewData["finalAmount"] = Math.Round(amount,2);
            return View();
        }
    }
}

Lab2/Views/Grades/IndexGrades.cshtml
@{
    ViewBag.Title = "IndexGrades";
}

<h2>Welcome to the grade calculator.</h2>
<h3>Enter your 3 latest grades down below.</h3>

@using (Html.BeginForm("IndexGrades", "Grades", FormMethod.Post))
{
    @Html.Label("First Grade")
    <br />
    @Html.TextBox("gradeOne")
    <br />
    @Html.Label("Second Grade")
    <br />
    @Html.TextBox("gradeTwo")
    <br />
    @Html.Label("Third Grade")
    <br />
    @Html.TextBox("gradeThree")
    <br />
    <br />
    <input type="submit" />
}

@if (ViewData["letterGrade"] != null)
{
    if (ViewData["letterGrade"] == "Your letter grade is A" || ViewData["letterGrade"] == "Your letter grade is B")
    {
        <h3 style="color:green">@ViewData["letterGrade"]</h3>
    }
    else if (ViewData["letterGrade"] == "Your letter grade is C")
    {
        <h3 style="color:yellow">@ViewData["letterGrade"]</h3>
    }
    else 
    {
        <h3 style="color:red">@ViewData["letterGrade"]</h3>
    }

}

Lab2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index page</h2>

<h2>@Html.ActionLink("Loans", "IndexLoan", "Loan")</h2><br />
<h2>@Html.ActionLink("Grades", "IndexGrades", "Grades")</h2>

Lab2/Views/Loan/IndexLoan.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to the Loan Calculator!</h2>
<h3>Fill out the form below to find out how rich you will be in the future.</h3>
<br />
<br />

<form action="@Url.Action("IndexLoan","Loan")" method="post">
    Years<br />
        <input id="years" name="years" type="number"/><br />
    Investment amount<br />
        <input id="amount" name="amount" type="number"/><br />
    Interest rate<br />
        <input id="rate" name="rate" type="number"/><br />
    <input type="submit" />
</form>

@if (ViewData["years"] != null || ViewData["amount"] != null || ViewData["rate"] != null)
{
<h3>Given @ViewData["years"] years, an investment of $@ViewData["amount"], and an annual rate of @ViewData["rate"]%, you will have $@ViewData["finalAmount"]</h3>
}

Lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>